### PR TITLE
Component Updated: Footer Component Implemented

### PR DESCRIPTION
**Pull request by suryanshsingh2001**
### Changes Made:

- [x] Added props to the `CustomFooter.jsx` component to customize background color, navlink hover color, and logo URL.
- [x] Updated the `CustomFooter` component to utilize these props for customization.
- [x] Added it to the `FooterPage`.
- [x] Documented the code according to industry standards.
- [x] Added Font Awesome dependencies to `package.json`.

### Proposed Changes:

- Enhance the `Footer` component by providing customization options for background color, navlink hover color, and logo URL.
- Improve the flexibility of the `Footer` component to accommodate various design requirements.
- Ensure that the code is well-documented and follows industry standards.
- Include Font Awesome dependencies in the project to enable the usage of icons in the `Footer` component.

### Related Issues:
[Implement Footer Component](https://github.com/vaishnavi-3969/Web-Componentify/issues/9)

### Screenshot:
image

### Additonal Notes
@vaishnavi-3969 
Please review this PR and provide your feedback. Your input is highly valuable for ensuring the quality of the project.

### HacktoberFest
To make this PR eligible for Hacktoberfest, please consider labeling it as `hacktoberfest-accepted` once reviewed and approved.

### CODE REVIEW

**Comment by vaishnavi-3969** [comment]
can you pls resolve conflicts :)

**Comment by suryanshsingh2001** [comment]
I think have I figured out the issue, earlier we had `App.jsx` and `Footer.jsx`. But since in #17 the contributor has changed the file to `Footer.js` and 'App.js' instead. Hence, I can proceed to make those files back to jsx or make mine in to js. 
It is advised to use jsx over js as it helps make the code simpler and allows easy use of HTML.

**Comment by suryanshsingh2001** [comment]
@vaishnavi-3969  Working on fixing all the merge conflicts

**Comment by suryanshsingh2001** [comment]
@vaishnavi-3969 All merged conficts are fixed now! Please review and merge it.

**Comment by vaishnavi-3969** [comment]
Thanks for your valuable contribution. Your PR is merged 😄

**Pull request merged**
