### PR TITLE
FlipKart-Clone

### PR DESCRIPTION
**Pull request by Nandinics04**

### CODE REVIEW

**Comment by Nandinics04** [comment]
@vaishnavi-3969 
please review my pull request on Online-Shopping-Website

**Comment by Nandinics04** [comment]
@vaishnavi-3969 
pls tell me if any changes needed in it.

**Comment by Nandinics04** [comment]
@vaishnavi-3969 please review my pull request

**Review by vaishnavi-3969 — APPROVED** [review]
LGTM!

**Comment by vaishnavi-3969** [comment]
Hey @Nandinics04 thanks for the amazing contribution! 😄

**Comment by Nandinics04** [comment]
Thank you @vaishnavi-3969 for reviewing my pr.

**Pull request merged**
